# Site settings
title: Brave New World
email: mts.cesario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matheus-santos.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  matheus-santos
repository: matheus-santos/matheus-santos.github.io
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
